# Generated by Django 3.2.8 on 2021-10-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20211030_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorities',
            name='image',
        ),
    ]
